@startuml
'https://plantuml.com/class-diagram

interface FlyBehavior{
    fly()
}
class WithWings{
    fly()
}
class FlyNoWay{
    fly()
}
FlyBehavior <|.. FlyNoWay
FlyBehavior <|.. WithWings

@enduml